//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAS.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động.
        /// </summary>
        public static string key_action {
            get {
                return ResourceManager.GetString("key_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        public static string key_agent {
            get {
                return ResourceManager.GetString("key_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đại lý.
        /// </summary>
        public static string key_agentinfo {
            get {
                return ResourceManager.GetString("key_agentinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp dụng.
        /// </summary>
        public static string key_apdung {
            get {
                return ResourceManager.GetString("key_apdung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chác chắn.
        /// </summary>
        public static string key_bancochacchan {
            get {
                return ResourceManager.GetString("key_bancochacchan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string key_cancel {
            get {
                return ResourceManager.GetString("key_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string key_capnhat {
            get {
                return ResourceManager.GetString("key_capnhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật dữ liệu thành công.
        /// </summary>
        public static string key_capnhatdulieuthanhcong {
            get {
                return ResourceManager.GetString("key_capnhatdulieuthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật số liệu.
        /// </summary>
        public static string key_capnhatsolieu {
            get {
                return ResourceManager.GetString("key_capnhatsolieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa có tài khoản?.
        /// </summary>
        public static string key_chuacotaikhoan {
            get {
                return ResourceManager.GetString("key_chuacotaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved.
        /// </summary>
        public static string key_chuaduyet {
            get {
                return ResourceManager.GetString("key_chuaduyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string key_close {
            get {
                return ResourceManager.GetString("key_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulation tools.
        /// </summary>
        public static string key_congcuthaotac {
            get {
                return ResourceManager.GetString("key_congcuthaotac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search tools.
        /// </summary>
        public static string key_congcutimkiem {
            get {
                return ResourceManager.GetString("key_congcutimkiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản.
        /// </summary>
        public static string key_dangkytaikhoan {
            get {
                return ResourceManager.GetString("key_dangkytaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        public static string key_dangxuly {
            get {
                return ResourceManager.GetString("key_dangxuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string key_delete {
            get {
                return ResourceManager.GetString("key_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi trạng thái thành công.
        /// </summary>
        public static string key_doitrangthaithanhcong {
            get {
                return ResourceManager.GetString("key_doitrangthaithanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi trạng thái thất bại.
        /// </summary>
        public static string key_doitrangthaithatbai {
            get {
                return ResourceManager.GetString("key_doitrangthaithatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string key_donhang {
            get {
                return ResourceManager.GetString("key_donhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt dòng.
        /// </summary>
        public static string key_duyetdong {
            get {
                return ResourceManager.GetString("key_duyetdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply All.
        /// </summary>
        public static string key_duyettatca {
            get {
                return ResourceManager.GetString("key_duyettatca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string key_hoanthanh {
            get {
                return ResourceManager.GetString("key_hoanthanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string key_home {
            get {
                return ResourceManager.GetString("key_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string key_hoso {
            get {
                return ResourceManager.GetString("key_hoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string key_icon {
            get {
                return ResourceManager.GetString("key_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Excel.
        /// </summary>
        public static string key_importexcel {
            get {
                return ResourceManager.GetString("key_importexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ.
        /// </summary>
        public static string key_Lake {
            get {
                return ResourceManager.GetString("key_Lake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới.
        /// </summary>
        public static string key_lammoi {
            get {
                return ResourceManager.GetString("key_lammoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại Nguyên liệu.
        /// </summary>
        public static string key_loainguyenlieu {
            get {
                return ResourceManager.GetString("key_loainguyenlieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string key_login {
            get {
                return ResourceManager.GetString("key_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập bằng email của bạn.
        /// </summary>
        public static string key_loginemail {
            get {
                return ResourceManager.GetString("key_loginemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Thông Tin.
        /// </summary>
        public static string key_management_info {
            get {
                return ResourceManager.GetString("key_management_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string key_map {
            get {
                return ResourceManager.GetString("key_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu Excel.
        /// </summary>
        public static string key_mauexcel {
            get {
                return ResourceManager.GetString("key_mauexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa dòng __0__ đã chọn không?.
        /// </summary>
        public static string key_msgconfirmdelete {
            get {
                return ResourceManager.GetString("key_msgconfirmdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string key_ngonngu {
            get {
                return ResourceManager.GetString("key_ngonngu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên file excel.
        /// </summary>
        public static string key_nhaptenfileexcel {
            get {
                return ResourceManager.GetString("key_nhaptenfileexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà vườn.
        /// </summary>
        public static string key_nhavuon {
            get {
                return ResourceManager.GetString("key_nhavuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to của.
        /// </summary>
        public static string key_of {
            get {
                return ResourceManager.GetString("key_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string key_Order {
            get {
                return ResourceManager.GetString("key_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng.
        /// </summary>
        public static string key_orderinfo {
            get {
                return ResourceManager.GetString("key_orderinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý đơn hàng.
        /// </summary>
        public static string key_quanlydonhang {
            get {
                return ResourceManager.GetString("key_quanlydonhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý người dùng.
        /// </summary>
        public static string key_quanlynguoidung {
            get {
                return ResourceManager.GetString("key_quanlynguoidung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string key_quenmatkhau {
            get {
                return ResourceManager.GetString("key_quenmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại.
        /// </summary>
        public static string key_reload {
            get {
                return ResourceManager.GetString("key_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước trang.
        /// </summary>
        public static string key_rowperpage {
            get {
                return ResourceManager.GetString("key_rowperpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string key_save {
            get {
                return ResourceManager.GetString("key_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string key_setting {
            get {
                return ResourceManager.GetString("key_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tất cả.
        /// </summary>
        public static string key_showall {
            get {
                return ResourceManager.GetString("key_showall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string key_signup {
            get {
                return ResourceManager.GetString("key_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đơn hàng.
        /// </summary>
        public static string key_taodonhang {
            get {
                return ResourceManager.GetString("key_taodonhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đơn hàng mới.
        /// </summary>
        public static string key_taodonhangmoi {
            get {
                return ResourceManager.GetString("key_taodonhangmoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đơn hàng thành công.
        /// </summary>
        public static string key_taodonhangthanhcong {
            get {
                return ResourceManager.GetString("key_taodonhangthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đơn hàng thất bại.
        /// </summary>
        public static string key_taodonhangthatbai {
            get {
                return ResourceManager.GetString("key_taodonhangthatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản.
        /// </summary>
        public static string key_taotaikhoan {
            get {
                return ResourceManager.GetString("key_taotaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Template.
        /// </summary>
        public static string key_templatepdf {
            get {
                return ResourceManager.GetString("key_templatepdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string key_them {
            get {
                return ResourceManager.GetString("key_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string key_themmoi {
            get {
                return ResourceManager.GetString("key_themmoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Excel thành công.
        /// </summary>
        public static string key_thongbaonhapexcel {
            get {
                return ResourceManager.GetString("key_thongbaonhapexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Excel thành công.
        /// </summary>
        public static string key_thongbaonhapexcelthanhcong {
            get {
                return ResourceManager.GetString("key_thongbaonhapexcelthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Excel thất bại.
        /// </summary>
        public static string key_thongbaonhapexcelthatbai {
            get {
                return ResourceManager.GetString("key_thongbaonhapexcelthatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete it?.
        /// </summary>
        public static string key_thongbaoxacnhanxoa {
            get {
                return ResourceManager.GetString("key_thongbaoxacnhanxoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất Excel thành công.
        /// </summary>
        public static string key_thongbaoxuatexcel {
            get {
                return ResourceManager.GetString("key_thongbaoxuatexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất Excel thành công.
        /// </summary>
        public static string key_thongbaoxuatexcelthanhcong {
            get {
                return ResourceManager.GetString("key_thongbaoxuatexcelthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất Excel thất bại.
        /// </summary>
        public static string key_thongbaoxuatexcelthatbai {
            get {
                return ResourceManager.GetString("key_thongbaoxuatexcelthatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thông tin đơn hàng.
        /// </summary>
        public static string key_thongtindonhang {
            get {
                return ResourceManager.GetString("key_thongtindonhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhà vườn.
        /// </summary>
        public static string key_thongtinnhavuon {
            get {
                return ResourceManager.GetString("key_thongtinnhavuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng anh.
        /// </summary>
        public static string key_tienganh {
            get {
                return ResourceManager.GetString("key_tienganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng việt.
        /// </summary>
        public static string key_tiengviet {
            get {
                return ResourceManager.GetString("key_tiengviet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng đại lý.
        /// </summary>
        public static string key_tongdaily {
            get {
                return ResourceManager.GetString("key_tongdaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng nhà vườn.
        /// </summary>
        public static string key_tongnhavuon {
            get {
                return ResourceManager.GetString("key_tongnhavuon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng quan.
        /// </summary>
        public static string key_tongquan {
            get {
                return ResourceManager.GetString("key_tongquan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số lượng nguyên liệu đã thu mua.
        /// </summary>
        public static string key_tongsoluongnguyenlieudamua {
            get {
                return ResourceManager.GetString("key_tongsoluongnguyenlieudamua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thành phẩm đã vận chuyển.
        /// </summary>
        public static string key_tongthanhphamdavanchuyen {
            get {
                return ResourceManager.GetString("key_tongthanhphamdavanchuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string key_trangthai {
            get {
                return ResourceManager.GetString("key_trangthai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy xuất nguồn gốc.
        /// </summary>
        public static string key_truyxuatnguongoc {
            get {
                return ResourceManager.GetString("key_truyxuatnguongoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khóa.
        /// </summary>
        public static string key_tukhoa {
            get {
                return ResourceManager.GetString("key_tukhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string key_update {
            get {
                return ResourceManager.GetString("key_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn.
        /// </summary>
        public static string key_vuilongchon {
            get {
                return ResourceManager.GetString("key_vuilongchon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn trạng thái.
        /// </summary>
        public static string key_vuilongchontrangthai {
            get {
                return ResourceManager.GetString("key_vuilongchontrangthai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string key_xoa {
            get {
                return ResourceManager.GetString("key_xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string key_xoadachon {
            get {
                return ResourceManager.GetString("key_xoadachon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu này?.
        /// </summary>
        public static string key_xoadulieunay {
            get {
                return ResourceManager.GetString("key_xoadulieunay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string key_xoaloc {
            get {
                return ResourceManager.GetString("key_xoaloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string key_xoathanhcong {
            get {
                return ResourceManager.GetString("key_xoathanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thất bại.
        /// </summary>
        public static string key_xoathatbai {
            get {
                return ResourceManager.GetString("key_xoathatbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất Excel.
        /// </summary>
        public static string key_xuatexcel {
            get {
                return ResourceManager.GetString("key_xuatexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đúng.
        /// </summary>
        public static string key_yes {
            get {
                return ResourceManager.GetString("key_yes", resourceCulture);
            }
        }
    }
}
